import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { X, Trash2, ArrowRight, History, Calendar, BookOpen } from 'lucide-react';
export const HistoryDrawer = ({ isOpen, onClose, history, onSelect, onClear, onDeleteItem, }) => {
    if (!isOpen)
        return null;
    return (_jsx("div", { className: "fixed inset-0 z-50 overflow-hidden bg-slate-900/40 backdrop-blur-xs flex justify-end", children: _jsxs("div", { className: "bg-white w-full max-w-md h-full shadow-2xl flex flex-col border-l border-slate-200 animate-in slide-in-from-right duration-200", children: [_jsxs("div", { className: "p-4 sm:p-5 border-b border-slate-200 flex items-center justify-between bg-slate-50", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(History, { className: "w-5 h-5 text-emerald-800" }), _jsxs("div", { children: [_jsx("h3", { className: "text-sm sm:text-base font-bold text-slate-900", children: "Historial de Gu\u00EDas Curadas" }), _jsxs("p", { className: "text-xs text-slate-500", children: [history.length, " ", history.length === 1 ? 'guía guardada' : 'guías guardadas'] })] })] }), _jsx("button", { onClick: onClose, className: "p-1 rounded-lg text-slate-400 hover:text-slate-600 hover:bg-slate-200 transition-colors", children: _jsx(X, { className: "w-5 h-5" }) })] }), _jsx("div", { className: "flex-1 overflow-y-auto p-4 space-y-3", children: history.length === 0 ? (_jsxs("div", { className: "text-center py-16 text-slate-400 space-y-2", children: [_jsx(BookOpen, { className: "w-10 h-10 mx-auto stroke-1" }), _jsx("p", { className: "text-sm font-medium", children: "A\u00FAn no hay gu\u00EDas en el historial" }), _jsx("p", { className: "text-xs text-slate-400 max-w-xs mx-auto", children: "Las secciones de Recursos de Actualidad que generes se guardar\u00E1n autom\u00E1ticamente aqu\u00ED para su reutilizaci\u00F3n." })] })) : (history.map((item, idx) => (_jsxs("div", { className: "bg-slate-50 hover:bg-white border border-slate-200 hover:border-emerald-500 rounded-xl p-3.5 transition-all text-xs space-y-2 group", children: [_jsxs("div", { className: "flex items-start justify-between gap-2", children: [_jsx("h4", { className: "font-bold text-slate-900 line-clamp-1 group-hover:text-emerald-900", children: item.topic }), _jsx("button", { onClick: (e) => {
                                            e.stopPropagation();
                                            onDeleteItem(idx);
                                        }, className: "text-slate-400 hover:text-rose-600 p-1 opacity-0 group-hover:opacity-100 transition-opacity", title: "Eliminar del historial", children: _jsx(Trash2, { className: "w-3.5 h-3.5" }) })] }), _jsxs("div", { className: "text-slate-500 text-[11px] flex items-center justify-between", children: [_jsxs("span", { className: "flex items-center gap-1", children: [_jsx(Calendar, { className: "w-3 h-3 text-slate-400" }), new Date(item.timestamp).toLocaleDateString()] }), _jsxs("span", { className: "font-medium text-emerald-800 bg-emerald-50 px-2 py-0.5 rounded", children: [item.resources.length, " recursos"] })] }), _jsxs("button", { onClick: () => {
                                    onSelect(item);
                                    onClose();
                                }, className: "w-full mt-2 py-1.5 px-3 bg-white hover:bg-emerald-700 hover:text-white border border-slate-200 hover:border-emerald-700 text-slate-700 rounded-lg text-xs font-semibold flex items-center justify-center gap-1.5 transition-colors", children: [_jsx("span", { children: "Cargar en el editor" }), _jsx(ArrowRight, { className: "w-3.5 h-3.5" })] })] }, idx)))) }), history.length > 0 && (_jsxs("div", { className: "p-4 border-t border-slate-200 bg-slate-50 flex justify-between items-center text-xs", children: [_jsx("span", { className: "text-slate-500", children: "Almacenado localmente" }), _jsx("button", { onClick: onClear, className: "text-rose-600 hover:text-rose-800 font-semibold hover:underline", children: "Borrar todo el historial" })] }))] }) }));
};
