import { Fragment as _Fragment, jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { REACTOR_TYPES_DATA } from '../data/reactorsCurriculum';
import { Timer, RotateCw, ArrowRightCircle, Boxes, Flame, Check, ChevronRight, BookOpen, Activity } from 'lucide-react';
export const ReactorWhiteboard = ({ selectedReactorId, onSelectReactor, }) => {
    const getIcon = (shortCode) => {
        switch (shortCode) {
            case 'BATCH':
                return _jsx(Timer, { className: "w-4 h-4 text-amber-400" });
            case 'CSTR':
                return _jsx(RotateCw, { className: "w-4 h-4 text-emerald-400" });
            case 'PFR':
                return _jsx(ArrowRightCircle, { className: "w-4 h-4 text-cyan-400" });
            case 'PBR':
                return _jsx(Boxes, { className: "w-4 h-4 text-purple-400" });
            default:
                return _jsx(Flame, { className: "w-4 h-4 text-orange-400" });
        }
    };
    return (_jsxs("div", { className: "bg-slate-900/90 backdrop-blur-md rounded-2xl border-2 border-slate-700/80 shadow-2xl p-5 sm:p-6 text-white space-y-5 overflow-hidden relative", children: [_jsx("div", { className: "absolute -top-24 -right-24 w-96 h-96 bg-gradient-to-br from-orange-500/20 via-amber-500/10 to-transparent rounded-full blur-3xl pointer-events-none" }), _jsx("div", { className: "absolute -bottom-24 -left-24 w-96 h-96 bg-gradient-to-tr from-cyan-500/20 via-emerald-500/10 to-transparent rounded-full blur-3xl pointer-events-none" }), _jsxs("div", { className: "relative z-10 flex flex-wrap items-center justify-between gap-3 border-b border-slate-700/80 pb-4", children: [_jsxs("div", { children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsxs("span", { className: "px-2.5 py-0.5 rounded-full text-xs font-black uppercase tracking-wider bg-orange-500 text-slate-950 shadow-md shadow-orange-500/30 flex items-center gap-1.5", children: [_jsx(Flame, { className: "w-3.5 h-3.5 fill-slate-950" }), " Taller de Planta Piloto"] }), _jsxs("span", { className: "text-xs text-amber-300 font-semibold hidden sm:inline-flex items-center gap-1", children: [_jsx(Activity, { className: "w-3.5 h-3.5" }), " Procesos Qu\u00EDmicos \u2022 Ingenier\u00EDa de Reactores"] })] }), _jsxs("h3", { className: "text-lg sm:text-xl font-black text-white mt-1.5 tracking-tight flex items-center gap-2", children: [_jsx("span", { children: "Diferentes Tipos de Reactores:" }), _jsx("span", { className: "text-transparent bg-clip-text bg-gradient-to-r from-amber-400 via-orange-400 to-rose-400 font-black", children: "BATCH, CSTR, PFR, PBR" })] })] }), _jsxs("div", { className: "text-right", children: [_jsx("span", { className: "text-xs text-slate-400 block font-medium", children: "Tema Focalizado:" }), _jsx("span", { className: "text-xs sm:text-sm font-bold text-amber-400 font-mono", children: "Dise\u00F1o y Tipo de Reactores" })] })] }), _jsx("div", { className: "relative z-10 grid grid-cols-2 sm:grid-cols-5 gap-2", children: REACTOR_TYPES_DATA.map((r) => {
                    const isSelected = selectedReactorId === r.id;
                    return (_jsxs("button", { onClick: () => onSelectReactor(r), className: `p-3 rounded-xl border text-left transition-all duration-200 relative overflow-hidden group cursor-pointer ${isSelected
                            ? 'border-orange-400 bg-slate-800/95 shadow-lg shadow-orange-500/20 ring-2 ring-orange-400/50 scale-[1.02]'
                            : 'border-slate-700 bg-slate-800/50 hover:bg-slate-800 hover:border-slate-600'}`, children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { className: "font-mono text-xs font-extrabold px-1.5 py-0.5 rounded bg-slate-900 border border-slate-700 text-slate-200 group-hover:text-white", children: r.shortCode }), getIcon(r.shortCode)] }), _jsx("div", { className: "text-xs font-bold text-slate-200 mt-2 line-clamp-1 group-hover:text-white", children: r.name.split(':')[0] }), _jsx("div", { className: "text-[10px] text-slate-400 mt-0.5 line-clamp-1", children: r.residenceTimeExample }), isSelected && (_jsx("div", { className: "absolute bottom-0 left-0 right-0 h-1 bg-gradient-to-r from-orange-400 via-amber-400 to-yellow-400" }))] }, r.id));
                }) }), _jsxs("div", { className: "relative z-10 bg-slate-950/70 border border-slate-800 rounded-xl overflow-hidden shadow-inner", children: [_jsxs("div", { className: "px-4 py-2.5 bg-slate-900/80 border-b border-slate-800 flex items-center justify-between text-xs font-bold text-slate-300", children: [_jsxs("span", { className: "uppercase tracking-wider flex items-center gap-1.5 text-amber-400", children: [_jsx(BookOpen, { className: "w-3.5 h-3.5" }), "Matriz Comparativa de Dise\u00F1o (Pizarra de Laboratorio):"] }), _jsx("span", { className: "text-[11px] text-slate-400 font-normal", children: "Haz clic en cualquier reactor para cargar sus recursos de actualidad" })] }), _jsx("div", { className: "overflow-x-auto", children: _jsxs("table", { className: "w-full text-left text-xs", children: [_jsx("thead", { children: _jsxs("tr", { className: "border-b border-slate-800 bg-slate-900/40 text-[11px] font-bold text-slate-400 uppercase tracking-wider", children: [_jsx("th", { className: "py-2.5 px-3.5", children: "Reactor" }), _jsx("th", { className: "py-2.5 px-3.5", children: "Modo de Operaci\u00F3n" }), _jsx("th", { className: "py-2.5 px-3.5", children: "Tiempo Residencia (\u03C4)" }), _jsx("th", { className: "py-2.5 px-3.5", children: "Ecuaci\u00F3n de Dise\u00F1o" }), _jsx("th", { className: "py-2.5 px-3.5", children: "Aplicaciones Industriales" }), _jsx("th", { className: "py-2.5 px-3.5 text-right", children: "Acci\u00F3n" })] }) }), _jsx("tbody", { className: "divide-y divide-slate-800/60 font-sans", children: REACTOR_TYPES_DATA.filter((x) => x.id !== 'general').map((item) => {
                                        const isSelected = selectedReactorId === item.id;
                                        return (_jsxs("tr", { onClick: () => onSelectReactor(item), className: `cursor-pointer transition-colors ${isSelected
                                                ? 'bg-orange-500/15 text-white'
                                                : 'hover:bg-slate-800/40 text-slate-300'}`, children: [_jsx("td", { className: "py-2.5 px-3.5 font-bold", children: _jsxs("div", { className: "flex items-center gap-2", children: [getIcon(item.shortCode), _jsx("span", { className: "font-mono text-amber-300 font-bold", children: item.shortCode })] }) }), _jsx("td", { className: "py-2.5 px-3.5 text-slate-300 font-medium", children: item.modeOfOperation }), _jsx("td", { className: "py-2.5 px-3.5 font-mono text-cyan-300", children: item.residenceTimeExample }), _jsx("td", { className: "py-2.5 px-3.5 font-mono text-emerald-300 text-[11px]", children: item.designEquation }), _jsx("td", { className: "py-2.5 px-3.5 text-slate-300 max-w-xs truncate", children: item.industrialApplications }), _jsx("td", { className: "py-2.5 px-3.5 text-right", children: _jsx("button", { onClick: (e) => {
                                                            e.stopPropagation();
                                                            onSelectReactor(item);
                                                        }, className: `px-2.5 py-1 rounded-md text-[11px] font-bold inline-flex items-center gap-1 transition-all ${isSelected
                                                            ? 'bg-orange-500 text-slate-950 shadow-xs'
                                                            : 'bg-slate-800 text-slate-300 hover:bg-orange-500 hover:text-slate-950'}`, children: isSelected ? (_jsxs(_Fragment, { children: [_jsx(Check, { className: "w-3 h-3" }), " Activo"] })) : (_jsxs(_Fragment, { children: [_jsx("span", { children: "Curar" }), _jsx(ChevronRight, { className: "w-3 h-3" })] })) }) })] }, item.id));
                                    }) })] }) })] })] }));
};
